[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[redirects]]
  from = "/env*"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/config*"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/webpack*"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/next.config.js"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/gatsby-config.js"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/svelte.config.js"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/src/*"
  to = "/404.html"
  status = 404
  force = true
